package nz.cri.gns.rapidalert.model;
// Generated 27/05/2014 4:27:09 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;


/**
 * DamageThreshold generated by hbm2java
 */
@Entity
@Table(name="damage_threshold")
@SequenceGenerator(name = "DAMAGE_THRESHOLD_SEQ", sequenceName = "DAMAGE_THRESHOLD_SEQ")
public class DamageThreshold  implements java.io.Serializable {


	// Fields    

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private int damageThresholdId;
	private BigDecimal threshold;


	// Constructors

	/** default constructor */
	public DamageThreshold() {
	}

	/** minimal constructor */
	public DamageThreshold(int damageThresholdId) {
		this.damageThresholdId = damageThresholdId;
	}

	/** full constructor */
	public DamageThreshold(int damageThresholdId, BigDecimal threshold) {
		this.damageThresholdId = damageThresholdId;
		this.threshold = threshold;
	}



	// Property accessors
	@Id
	@Column(name="damage_threshold_id", unique=true, nullable=false, insertable=true, updatable=true)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DAMAGE_THRESHOLD_SEQ")
	public int getDamageThresholdId() {
		return this.damageThresholdId;
	}

	public void setDamageThresholdId(int damageThresholdId) {
		this.damageThresholdId = damageThresholdId;
	}
	@Column(name="threshold", unique=false, nullable=true, insertable=true, updatable=true, precision=8, scale=6)

	public BigDecimal getThreshold() {
		return this.threshold;
	}

	public void setThreshold(BigDecimal threshold) {
		this.threshold = threshold;
	}









}
