package nz.cri.gns.rapidalert.model;
// Generated 27/05/2014 4:27:09 PM by Hibernate Tools 3.1.0.beta4

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;


/**
 * Region generated by hbm2java
 */
@Entity
@Table(name="region")
@SequenceGenerator(name = "REGION_SEQ", sequenceName = "REGION_SEQ")
public class Region  implements java.io.Serializable {


	private static final long serialVersionUID = 1L;
    // Fields    

     private int regionId;
     private String description;
     private Set<StationList> stationLists = new HashSet<StationList>(0);


    // Constructors

    /** default constructor */
    public Region() {
    }

	/** minimal constructor */
    public Region(int regionId) {
        this.regionId = regionId;
    }
    
    /** full constructor */
    public Region(int regionId, String description, Set<StationList> stationLists) {
        this.regionId = regionId;
        this.description = description;
        this.stationLists = stationLists;
    }
    

   
    // Property accessors
    @Id
    @Column(name="region_id", unique=true, nullable=false, insertable=true, updatable=true)
  	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "REGION_SEQ")
    public int getRegionId() {
        return this.regionId;
    }
    
    public void setRegionId(int regionId) {
        this.regionId = regionId;
    }
    @Column(name="description", unique=false, nullable=true, insertable=true, updatable=true, length=100)

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    @OneToMany(cascade={CascadeType.ALL}, fetch=FetchType.LAZY, mappedBy="region")

    public Set<StationList> getStationLists() {
        return this.stationLists;
    }
    
    public void setStationLists(Set<StationList> stationLists) {
        this.stationLists = stationLists;
    }
   








}
