package nz.cri.gns.rapidalert.model;
// Generated 27/05/2014 4:27:09 PM by Hibernate Tools 3.1.0.beta4

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;


/**
 * StationList generated by hbm2java
 */
@Entity
@Table(name="station_list")
@SequenceGenerator(name = "STATION_LIST_SEQ", sequenceName = "STATION_LIST_SEQ")
public class StationList  implements java.io.Serializable {


	private static final long serialVersionUID = 1L;
   // Fields    

     private int stationListId;
     private Region region;
     private String segment;
     private String siteCode;
     private String siteName;


    // Constructors

    /** default constructor */
    public StationList() {
    }

	/** minimal constructor */
    public StationList(int stationListId, Region region) {
        this.stationListId = stationListId;
        this.region = region;
    }
    
    /** full constructor */
    public StationList(int stationListId, Region region, String segment, String siteCode, String siteName) {
        this.stationListId = stationListId;
        this.region = region;
        this.segment = segment;
        this.siteCode = siteCode;
        this.siteName = siteName;
    }
    

   
    // Property accessors
    @Id
    @Column(name="station_list_id", unique=true, nullable=false, insertable=true, updatable=true)
  	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "STATION_LIST_SEQ")
    public int getStationListId() {
        return this.stationListId;
    }
    
    public void setStationListId(int stationListId) {
        this.stationListId = stationListId;
    }
    @ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
        @JoinColumn(name="region_id", unique=false, nullable=false, insertable=true, updatable=true)

    public Region getRegion() {
        return this.region;
    }
    
    public void setRegion(Region region) {
        this.region = region;
    }
    @Column(name="segment", unique=false, nullable=true, insertable=true, updatable=true, length=100)

    public String getSegment() {
        return this.segment;
    }
    
    public void setSegment(String segment) {
        this.segment = segment;
    }
    @Column(name="site_code", unique=false, nullable=true, insertable=true, updatable=true, length=4)

    public String getSiteCode() {
        return this.siteCode;
    }
    
    public void setSiteCode(String siteCode) {
        this.siteCode = siteCode;
    }
    @Column(name="site_name", unique=false, nullable=true, insertable=true, updatable=true, length=200)

    public String getSiteName() {
        return this.siteName;
    }
    
    public void setSiteName(String siteName) {
        this.siteName = siteName;
    }
   








}
