package nz.cri.gns.rapidalert.model;
// Generated 27/05/2014 4:27:09 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;


/**
 * Station generated by hbm2java
 */
@Entity
@Table(name="station")
@SequenceGenerator(name = "STATION_SEQ", sequenceName = "STATION_SEQ")
public class Station  implements java.io.Serializable {


	private static final long serialVersionUID = 1L;
   // Fields    

     private int stationId;
     private Earthquake earthquake;
     private String siteCode;
     private String siteName;
     private double pgaH1;
     private double pgaH2;
     private double pgaHLower;
     private double pgaHUpper;
     private double pgaV;
     private BigDecimal latitude;
     private BigDecimal longitude;
     private Integer distance;
     private Date dateAdded;
     private String accelerogramId;


    // Constructors

    /** default constructor */
    public Station() {
    }

	/** minimal constructor */
    public Station(int stationId, Earthquake earthquake, String accelerogramId) {
        this.stationId = stationId;
        this.earthquake = earthquake;
        this.accelerogramId = accelerogramId;
    }
    
    /** full constructor */
    public Station(int stationId, Earthquake earthquake, String siteCode, String siteName, double pgaH1, double pgaH2, double pgaHLower, double pgaHUpper, double pgaV, BigDecimal latitude, BigDecimal longitude, Integer distance, Date dateAdded, String accelerogramId) {
        this.stationId = stationId;
        this.earthquake = earthquake;
        this.siteCode = siteCode;
        this.siteName = siteName;
        this.pgaH1 = pgaH1;
        this.pgaH2 = pgaH2;
        this.pgaHLower = pgaHLower;
        this.pgaHUpper = pgaHUpper;
        this.pgaV = pgaV;
        this.latitude = latitude;
        this.longitude = longitude;
        this.distance = distance;
        this.dateAdded = dateAdded;
        this.accelerogramId = accelerogramId;
    }
    

   
    // Property accessors
    @Id
    @Column(name="station_id", unique=true, nullable=false, insertable=true, updatable=true)
  	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "STATION_SEQ")
    public int getStationId() {
        return this.stationId;
    }
    
    public void setStationId(int stationId) {
        this.stationId = stationId;
    }
    @ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
        @JoinColumn(name="eq_id", unique=false, nullable=false, insertable=true, updatable=true)

    public Earthquake getEarthquake() {
        return this.earthquake;
    }
    
    public void setEarthquake(Earthquake earthquake) {
        this.earthquake = earthquake;
    }
    @Column(name="site_code", unique=false, nullable=true, insertable=true, updatable=true, length=4)

    public String getSiteCode() {
        return this.siteCode;
    }
    
    public void setSiteCode(String siteCode) {
        this.siteCode = siteCode;
    }
    @Column(name="site_name", unique=false, nullable=true, insertable=true, updatable=true, length=200)

    public String getSiteName() {
        return this.siteName;
    }
    
    public void setSiteName(String siteName) {
        this.siteName = siteName;
    }
    @Column(name="pga_h1", unique=false, nullable=true, insertable=true, updatable=true, precision=8, scale=6)

    public double getPgaH1() {
        return this.pgaH1;
    }
    
    public void setPgaH1(double pgaH1) {
        this.pgaH1 = pgaH1;
    }
    @Column(name="pga_h2", unique=false, nullable=true, insertable=true, updatable=true, precision=8, scale=6)

    public double getPgaH2() {
        return this.pgaH2;
    }
    
    public void setPgaH2(double pgaH2) {
        this.pgaH2 = pgaH2;
    }
    @Column(name="pga_h_lower", unique=false, nullable=true, insertable=true, updatable=true, precision=8, scale=6)

    public double getPgaHLower() {
        return this.pgaHLower;
    }
    
    public void setPgaHLower(double pgaHLower) {
        this.pgaHLower = pgaHLower;
    }
    @Column(name="pga_h_upper", unique=false, nullable=true, insertable=true, updatable=true, precision=8, scale=6)

    public double getPgaHUpper() {
        return this.pgaHUpper;
    }
    
    public void setPgaHUpper(double pgaHUpper) {
        this.pgaHUpper = pgaHUpper;
    }
    @Column(name="pga_v", unique=false, nullable=true, insertable=true, updatable=true, precision=8, scale=6)

    public double getPgaV() {
        return this.pgaV;
    }
    
    public void setPgaV(double pgaV) {
        this.pgaV = pgaV;
    }
    @Column(name="latitude", unique=false, nullable=true, insertable=true, updatable=true, precision=8, scale=6)

    public BigDecimal getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }
    @Column(name="longitude", unique=false, nullable=true, insertable=true, updatable=true, precision=8, scale=6)

    public BigDecimal getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }
    @Column(name="distance", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getDistance() {
        return this.distance;
    }
    
    public void setDistance(Integer distance) {
        this.distance = distance;
    }
    @Column(name="date_added", unique=false, nullable=true, insertable=true, updatable=true, length=29)

    public Date getDateAdded() {
        return this.dateAdded;
    }
    
    public void setDateAdded(Date dateAdded) {
        this.dateAdded = dateAdded;
    }
    @Column(name="accelerogram_id", unique=false, nullable=false, insertable=true, updatable=true, length=30)

    public String getAccelerogramId() {
        return this.accelerogramId;
    }
    
    public void setAccelerogramId(String accelerogramId) {
        this.accelerogramId = accelerogramId;
    }
   








}
